### ISSUE TITLE
Not an Issue but a Question

### ISSUE THREAD

**Issue by xelcho** [stemmlerjs/khalilstemmler-website-2019#2]
I really enjoyed your articles surrounding solid principles. 

I would like to replicate the design symbols you used here (green boxes etc):
https://khalilstemmler.com/wiki/concrete-class/
Please forgive my ignorance: What are they called? Is there an extension/theme/ for something like libreoffice draw or some other free tool I can use to make these?
Thanks,
X

**Comment by stemmlerjs** [comment]
Hey @xelcho. For the _Class Diagrams_, I use a tool called [Figma](https://figma.com).

It's probably not really meant for doing that, but since Visual Paradigm isn't free, it's what I use :)

It's cool though, you can create "Components" and then re-use them, just plugging in the values you need.

![Screen Shot 2019-05-26 at 9 40 10 AM](https://user-images.githubusercontent.com/6892666/58382632-90a60000-7f9a-11e9-86e7-6ec491d473cf.png)

Thanks for reading the blog!

**Comment by xelcho** [comment]
This is great!
Thanks for the quick response!
I'll do you one better. If you can, please export your figures as svg and share them as I will try to make a libreoffice theme from them. :)

On your blog it is very good, I really appreciate your focus on SOLID.

**Comment by stemmlerjs** [comment]
Sure! Here you go:

https://github.com/stemmlerjs/khalilstemmler-website-2019/blob/master/static/img/wiki/concrete-classes/concrete-classes.svg

You can find all of my assets in the "/static/img" folder [right here](https://github.com/stemmlerjs/khalilstemmler-website-2019/tree/master/static/img).
